name: Build
on:
  push:
    branches-ignore:
      - 'gh-pages'
  pull_request:
    branches:
      - master

jobs:
  Test:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare
        run: |
          bundle update --bundler
          bundle install
      - name: Run tests
        env:
          SLACK_URL: ${{ secrets.SLACK_URL }}
        run: bundle exec fastlane test
